import type { Metadata } from "next";
import { Geist, Orbitron } from "next/font/google";
import "./globals.css";
import { Provider } from "@/app/providers";
import { ThemeToggleButton } from "@/shared/components/ui/ThemeToggle";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });
const orbitron = Orbitron({ subsets: ["latin"], variable: "--font-display" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geist.variable} ${orbitron.variable}`}>
      <body className="font-sans antialiased">
        <Provider>
          <nav className="flex justify-end px-4 py-2">
            <ThemeToggleButton />
          </nav>
          {children}
        </Provider>
      </body>
    </html>
  );
}
